### ISSUE TITLE
Document and test deployment to google cloud

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3820]
Google gives you $300 for a 90 day trial of Google cloud.
Sign up for that, then follow first 3 steps here to create a new project and install the google cloud CLI:
https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-ruby-service

Then follow these steps to deploy the site in a docker image on google cloud:
https://gist.github.com/iEv0lv3/8f877bbd3d27f6a670435bda0650d7d8

Use this page to help configure your build:
https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run

I almost have this working, but wanted to put my notes so far here:

1) Only a few 'regions' support the build process, so use some combination of these commands:
gcloud config set compute/region us-central1
gcloud builds submit --region=us-central1
gcloud compute project-info add-metadata --metadata google-compute-default-zone=us-centra11\n

2) Sample cloudbuild.yaml
```
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/websiteone-372019/websiteone-web', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/websiteone-372019/websiteone-web']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'websiteone-web', '--image', 'gcr.io/websiteone-372019/websiteone-web', '--region', 'us-central1']
images:
- gcr.io/websiteone-372019/websiteone-web
```

3) In the sample file above, I put the name of the  Google Service that I created called 'websiteone-web' which should create a permanent URL.
